name: Run Electron app
on:
  push:
  schedule:
    - cron: '0 7 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Start
        run: |
          yarn
          xvfb-maybe yarn start
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: |
          yarn
          xvfb-run yarn test
